-- MySQL Script generated by MySQL Workbench
-- sex 02 mai 2025 19:30:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fixwise
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fixwise
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `fixwise` DEFAULT CHARACTER SET utf8 ;
USE `fixwise` ;

-- -----------------------------------------------------
-- Table `fixwise`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fixwise`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF_CNPJ` VARCHAR(14) NOT NULL,
  `EmailContato` VARCHAR(45) NULL,
  `TelefoneContato` VARCHAR(15) NULL,
  `Logradouro` VARCHAR(45) NULL,
  `CEP` VARCHAR(9) NULL,
  `Cidade` VARCHAR(45) NULL,
  `Bairro` VARCHAR(45) NULL,
  `Numero` INT NULL,
  `UF` VARCHAR(2) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fixwise`.`Equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fixwise`.`Equipamento` (
  `idEquipamento` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Status` VARCHAR(10) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idEquipamento`),
  INDEX `fk_Equipamento_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Equipamento_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `fixwise`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fixwise`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fixwise`.`Funcionario` (
  `idUsuario` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  `TipoUsuario` INT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fixwise`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fixwise`.`Servico` (
  `idServico` INT NOT NULL,
  `TipoServico` VARCHAR(45) NULL,
  `DataInicio` DATE NULL,
  `DataFim` DATE NULL,
  `Status` VARCHAR(45) NULL,
  `Setor` VARCHAR(45) NULL,
  PRIMARY KEY (`idServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fixwise`.`OrdemServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fixwise`.`OrdemServico` (
  `idOrdemServico` INT NOT NULL,
  `Equipamento_idEquipamento` INT NOT NULL,
  `Servico_idServico` INT NOT NULL,
  PRIMARY KEY (`idOrdemServico`),
  INDEX `fk_OrdemServico_Equipamento1_idx` (`Equipamento_idEquipamento` ASC) VISIBLE,
  INDEX `fk_OrdemServico_Servico1_idx` (`Servico_idServico` ASC) VISIBLE,
  CONSTRAINT `fk_OrdemServico_Equipamento1`
    FOREIGN KEY (`Equipamento_idEquipamento`)
    REFERENCES `fixwise`.`Equipamento` (`idEquipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdemServico_Servico1`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `fixwise`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fixwise`.`ServicosFuncionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fixwise`.`ServicosFuncionario` (
  `idServicosFuncionario` INT NOT NULL,
  `Funcionario_idUsuario` INT NOT NULL,
  `Servico_idServico` INT NOT NULL,
  PRIMARY KEY (`idServicosFuncionario`),
  INDEX `fk_ServicosFuncionario_Funcionario1_idx` (`Funcionario_idUsuario` ASC) VISIBLE,
  INDEX `fk_ServicosFuncionario_Servico1_idx` (`Servico_idServico` ASC) VISIBLE,
  CONSTRAINT `fk_ServicosFuncionario_Funcionario1`
    FOREIGN KEY (`Funcionario_idUsuario`)
    REFERENCES `fixwise`.`Funcionario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ServicosFuncionario_Servico1`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `fixwise`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
